branches:
  except:
    - master
language: ruby
cache: bundler
sudo: false
bundler_args: --without local
rvm:
  - 2.3.1
env:
  - TEST_GROUP=1 CHEF_VERSION="~> 12.14"
  - TEST_GROUP=2 CHEF_VERSION="~> 12.14"
  - TEST_GROUP=3 CHEF_VERSION="~> 12.14"
  - TEST_GROUP=4 CHEF_VERSION="~> 12.14"
  - TEST_GROUP=5 CHEF_VERSION="~> 12.14"
  - TEST_GROUP=6 CHEF_VERSION="~> 12.14"
script:
  - bundle exec rubocop
  - bundle exec foodcritic -f any .
  - bundle exec parallel_test spec/unit/ -n 6 --only-group $TEST_GROUP --group-by filesize --type rspec
